// TECHKARO data base.
let techkaro = {
    courseName: "Web-development",
    students: [
        {
            studentname: "sofia",
            studentCNic: 42401-565565-5,
            studentContact: 03426537,
            isMarried: false,
            fatherName: "Hafeez",
            fatheCNic: 42401-5897965-4,
            fatherContact: 03524624545,
            qualification: "metric",
            dob: 14-05-1999,
            gander: "female",
            noOfSibllings: 5,
            hobbies: ["football player", "hockey"],
            isEmployed: false,
            fatheroccuay: "maneger",
            fatherInCome: 30000,
            persnolInCome: 10000,
            email: "sofia444@gmail.com",
            rollOn: 1,
            group: "A",
            address: "abc road site karachi",
            distance: "10km",
            extraSkills: ["Art", "singing"],
            profession: "web-developer",
            otherCourse: {
                courseName: "Beautision",
                institute: "memonfoundation",
                courseFee: 2500,
                instituteEmail: "memon@gmail.com",
                timing: "4PM-6PM",
                distance: "15km",
                duration: "6 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "wahida",
            studentCNic: 42401-255633-7,
            studentContact: 2164532135,
            isMarried: false,
            fatherName: "aabc",
            fatheCNic: 42401-5008965-4,
            fatherContact: 0345122545,
            qualification: "metric",
            dob: 04-02-1998,
            gander: "female",
            noOfSibllings: 1,
            hobbies: ["teaching", "coding"],
            isEmployed: false,
            fatheroccuay: "casher",
            fatherInCome: 50000,
            persnolInCome: 15000,
            email: "wahida454@gmail.com",
            rollOn: 2,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: ["desiging", "singing"],
            profession: "web-developer",
            otherCourse: {
                courseName:"CID",
                institute: "benazir institute",
                courseFee: 3000,
                instituteEmail: "abc@gmail.com",
                timing: "1PM-3PM",
                distance: "10km",
                duration: "4 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "somia",
            studentCNic: 42401-255633-7,
            studentContact: 2164532135,
            isMarried: false,
            fatherName: "aabc",
            fatheCNic: 42401-5008965-4,
            fatherContact: 0345122545,
            qualification: "BSC",
            dob: 04-04-1988,
            gander: "female",
            noOfSibllings: 4,
            hobbies: ["teaching", "coding"],
            isEmployed: false,
            fatheroccuay: "casher",
            fatherInCome: 50000,
            persnolInCome: 15000,
            email: "SOMIA454@gmail.com",
            rollOn: 3,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: ["desiging", "singing"],
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc institute",
                courseFee: 3000,
                instituteEmail: "abc@gmail.com",
                timing: "1PM-3PM",
                distance: "10km",
                duration: "4 months"
            },
            traveling: "bus",
            refreance: "through facebook"

        },
        {
            studentname: "Bineesh",
            studentCNic: 42401-565565-5,
            studentContact: 03426537,
            isMarried: true,
            husbandName: "abc",
            husbandCNic: 42401-5897965-4,
            husbandContact: 031274545,
            qualification: "metric",
            dob: 05-05-1987,
            gander: "female",
            noOfSibllings: 6,
            hobbies: "book-reading",
            isEmployed: false,
            husbandoccuay: "employ",
            husbandInCome: 20000,
            persnolInCome: 10000,
            email: "bineesh444@gmail.com",
            rollOn: 4,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "designer",
            profession: ["web-developer", "housewife", "designer"],
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 1000,
                instituteEmail: "abc@gmail.com",
                timing: "10AM-2PM",
                distance: "6km",
                duration: "6 months"
            },
            traveling: "bus",
            refreance: "through friend"
        },
        {
            studentname: "Saad",
            studentCNic: 42401-565565-5,
            studentContact: 03426537,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "matric",
            dob: 03-05-1989,
            gander: "male",
            noOfSibllings: 6,
            hobbies: "cricket",
            isEmployed: true,
            job: {
                companyName: "abc",
                salary: "15000",
                post: "self-employ",
                companyEmail: "abc345@gmail.com",
                timing: "9am-3pm",
                distance: "5km",
                duration: 1,
            },
            fatheroccuay: "casher",
            fatherInCome: 30000,
            persnolInCome: 15000,
            email: "saad444@gmail.com",
            rollOn: 5,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                instituteEmail: "abc@gmail.com",
                timing: "7PM-9PM",
                distance: "6km",
                duration: "2 months"
            },
            traveling: "bus",
            refreance: "through friend"
        },
        {
            studentname: "Uzair",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 03-05-1991,
            gander: "male",
            noOfSibllings: 4,
            hobbies: ["cricket", "football"],
            isEmployed: true,
            job: {
                officeName: "abc",
                salary: "15000",
                post: "countend",
                companyEmail: "abc345@gmail.com",
                timing: "9am-4pm",
                distance: "5km",
                duration: 1,
            },
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 15000,
            email: "uzair444@gmail.com",
            rollOn: 6,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "photoshop-designer",
            profession: ["web-developer", "photoshop"],
            otherCourse: {
                courseName: "MSoffice",
                institute: "abc",
                courseFee: 1500,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-9PM",
                distance: "6km",
                duration: "8 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "Sharik",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 01-04-1995,
            gander: "male",
            noOfSibllings: 3,
            hobbies: ["cricket", "football"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 5000,
            email: "sharik444@gmail.com",
            rollOn: 7,
            group: "A",
            address: "abc road site karachi",
            distance: "4km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-8PM",
                distance: "3km",
                duration: "3 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "Nida",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: true,
            job: "housewife",
            husbandName: "abc",
            husbandCNic: 42401-5897965-4,
            husbandContact: 031274545,
            qualification: "BSC",
            dob: 03-09-1988,
            gander: "female",
            noOfSibllings: 6,
            hobbies: "coding",
            isEmployed: false,
            husbandoccuay: "employ",
            husbandInCome: 20000,
            persnolInCome: 5000,
            email: "nida444@gmail.com",
            rollOn: 8,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 600,
                instituteEmail: "abc@gmail.com",
                timing: "10AM-12PM",
                distance: "5km",
                duration: "6 months"
            },
            traveling: "persnol",
            refreance: "through facebook"
        },
        {
            studentname: "Shazia",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: true,
            job: {
                instituteName: "abc school",
                work: "teacher",
                salary: 6000,
                timing: "8am-12:30pm",
                distance: "7km",
            },
            husbandName: "abc",
            husbandCNic: 42401-5897965-4,
            husbandContact: 031274545,
            qualification: "FSC",
            dob: 03-10-1989,
            gander: "female",
            noOfSibllings: 5,
            hobbies: "coding",
            isEmployed: true,
            husbandoccuay: "employ",
            husbandInCome: 15000,
            persnolInCome: 6000,
            email: "shazia444@gmail.com",
            rollOn: 9,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "tuitor",
            profession: ["teacher", "web-developer"],
            otherCourse: "nothing",
            traveling: "persnol",
            refreance: "through facebook"
        },
        {
            studentname: "Maham Javeed",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "Javeed",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "FSC",
            dob: 12-03-1997,
            gander: "female",
            noOfSibllings: 5,
            hobbies: "coding",
            isEmployed: true,
            job: {
                instituteName: "abc school",
                salary: 4000,
                profession: "teacher",
                timing: "8am-1pm",
                distance: "9km",
            },
            fatheroccuay: "employ",
            fatherInCome: 20000,
            persnolInCome: 8000,
            email: "maham444@gmail.com",
            rollOn: 10,
            group: "A",
            address: "abc road site karachi",
            distance: "2km",
            extraSkills: "tuitor",
            profession: ["teacher", "tuitor", "web-developer"],
            otherCourse: {
                courseName: "cloud-native",
                courseFee: 3000,
                institute: "abc",
                instituteEmail: "abc@gmail.com",
                timing: "11AM-2PM",
                distance: "4km",
                duration: "5 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "Arifa",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "BSC",
            dob: 03-09-1987,
            gander: "female",
            noOfSibllings: 4,
            hobbies: "coding",
            isemployes: false,
            fatheroccuay: "employ",
            fatherInCome: 25000,
            persnolInCome: 10000,
            email: "arifa444@gmail.com",
            rollOn: 11,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2500,
                instituteEmail: "abc@gmail.com",
                timing: "11AM-3PM",
                distance: "3km",
                duration: "3 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "Fabeeha Ahmed",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "Ahmed",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "FSC",
            dob: 10-01-1997,
            gander: "female",
            noOfSibllings: 2,
            hobbies: "coding",
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 20000,
            persnolInCome: 50000,
            email: "fabeehaahmed534@gmail.com",
            rollOn: 12,
            group: "A",
            address: "abc road site karachi",
            distance: "6km",
            extraSkills: "nothing",
            profession: "web-develpoer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 700,
                instituteEmail: "abc@gmail.com",
                timing: "12pM-2PM",
                distance: "1km",
                duration: "4 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "wajahat",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 01-04-1995,
            gander: "male",
            noOfSibllings: 3,
            hobbies: ["cricket", "football"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 5000,
            email: "wajahat444@gmail.com",
            rollOn: 13,
            group: "A",
            address: "abc road site karachi",
            distance: "4km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-8PM",
                distance: "3km",
                duration: "3 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "sameer",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 01-04-1995,
            gander: "male",
            noOfSibllings: 3,
            hobbies: ["cricket", "football"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 5000,
            email: "sameer444@gmail.com",
            rollOn: 14,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "4PM-6PM",
                distance: "9km",
                duration: "8 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "Ali Raza",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 04-01-1999,
            gander: "male",
            noOfSibllings: 2,
            hobbies: ["coding", "programming"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 5000,
            email: "aliraza444@gmail.com",
            rollOn: 15,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-9PM",
                distance: "9km",
                duration: "12 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "fahmeen",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 04-01-1989,
            gander: "female",
            noOfSibllings: 2,
            hobbies: "coding",
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 20000,
            persnolInCome: 10000,
            email: "fehmeen444@gmail.com",
            rollOn: 16,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-9PM",
                distance: "6km",
                duration: "4 months"
            },
            traveling: "persnol",
            refreance: "through facebook"
        },
        {
            studentname: "awis",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 25-12-1995,
            gander: "male",
            noOfSibllings: 2,
            hobbies: ["coding", "reading", "cricket"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 15000,
            persnolInCome: 5000,
            email: "awis444@gmail.com",
            rollOn: 17,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-9PM",
                distance: "9km",
                duration: "12 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "nadir",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 04-08-1999,
            gander: "male",
            noOfSibllings: 4,
            hobbies: ["coding", "football"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 5000,
            email: "nadir444@gmail.com",
            rollOn: 18,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-9PM",
                distance: "1km",
                duration: "6 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "jamila",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 15-03-1989,
            gander: "female",
            noOfSibllings: 5,
            hobbies: "coding",
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 25000,
            persnolInCome: 10000,
            email: "jamila444@gmail.com",
            rollOn: 19,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 3000,
                instituteEmail: "abc@gmail.com",
                timing: "6PM-9PM",
                distance: "5km",
                duration: "9 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "sana",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 04-6-1994,
            gander: "female",
            noOfSibllings: 6,
            hobbies: ["coding", "makeup"],
            isEmployed: true,
            job: [
                {
                  officeName: "abc",
                  salary: 20000,
                  timing: "9am-3pm",
                  distance: "2km",
                }
            ],
            fatheroccuay: "employ",
            fatherInCome: 10000,
            persnolInCome: 5000,
            email: "sana444@gmail.com",
            rollOn: 20,
            group: "A",
            address: "abc road site karachi",
            distance: "7km",
            extraSkills: "graphic-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2500,
                instituteEmail: "abc@gmail.com",
                timing: "4PM-6PM",
                distance: "5km",
                duration: "10 months"
            },
            traveling: "bus",
            refreance: "through facebook"
        },
        {
            studentname: "farheen",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 04-01-1999,
            gander: "female",
            noOfSibllings: 4,
            hobbies: ["coding", "singing"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 30000,
            persnolInCome: 10000,
            email: "farheen444@gmail.com",
            rollOn: 21,
            group: "A",
            address: "abc road site karachi",
            distance: "2km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 6000,
                instituteEmail: "abc@gmail.com",
                timing: "10aM-1PM",
                distance: "8km",
                duration: "7 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "nazia",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "inter",
            dob: 24-07-1999,
            gander: "female",
            noOfSibllings: 4,
            hobbies: ["coding", "singing"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 35000,
            persnolInCome: 10000,
            email: "nazia444@gmail.com",
            rollOn: 22,
            group: "A",
            address: "abc road site karachi",
            distance: "2km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 6000,
                instituteEmail: "abc@gmail.com",
                timing: "10aM-1PM",
                distance: "8km",
                duration: "7 months"
            },
            traveling: "auto",
            refreance: "through facebook"
        },
        {
        studentname: "ayesha",
            studentCNic: 42401-565565-5,
            studentContact: 033356637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 031274545,
            qualification: "BSC",
            dob: 14-01-1989,
            gander: "female",
            noOfSibllings: 4,
            hobbies: "coding",
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 25000,
            persnolInCome: 10000,
            email: "ayesha444@gmail.com",
            rollOn: 23,
            group: "A",
            address: "abc road site karachi",
            distance: "6km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 1000,
                instituteEmail: "abc@gmail.com",
                timing: "11aM-1PM",
                distance: "4km",
                duration: "6 months"
            },
            traveling: "personal",
            refreance: "through facebook"
        },
        {
            studentname: "talia",
            studentCNic: 42401-565565-5,
            studentContact: 032336637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 0332374545,
            qualification: "BSC",
            dob: 14-01-1997,
            gander: "female",
            noOfSibllings: 4,
            hobbies: ["coding", "art"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 40000,
            persnolInCome: 15000,
            email: "talia444@gmail.com",
            rollOn: 24,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "nothing",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 1000,
                instituteEmail: "abc@gmail.com",
                timing: "12aM-2PM",
                distance: "3km",
                duration: "4 months"
            },
            traveling: "auto",
            refreance: "through friend"
        },
        {
            studentname: "halima",
            studentCNic: 42401-565565-5,
            studentContact: 032536637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 0332374545,
            qualification: "BSC",
            dob: 28-6-1987,
            gander: "female",
            noOfSibllings: 4,
            hobbies: ["coding", "art"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 40000,
            persnolInCome: 15000,
            email: "hamila444@gmail.com",
            rollOn: 25,
            group: "A",
            address: "abc road site karachi",
            distance: "5km",
            extraSkills: "no",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 6000,
                instituteEmail: "abc@gmail.com",
                timing: "10aM-1PM",
                distance: "8km",
                duration: "7 months"
            },
            traveling: "persnol-bike",
            refreance: "through facebook"
        },
        {
            studentname: "Altaf Hussain",
            studentCNic: 42401-565565-5,
            studentContact: 032336637,
            isMarried: false,
            fatherName: "abc",
            fatherCNic: 42401-5897965-4,
            fatherContact: 0332374545,
            qualification: "BSC",
            dob: 30-04-1987,
            gander: "male",
            noOfSibllings: 9,
            hobbies: ["coding", "art"],
            isEmployed: false,
            fatheroccuay: "employ",
            fatherInCome: 20000,
            persnolInCome: 15000,
            email: "altaf444@gmail.com",
            rollOn: 26,
            group: "A",
            address: "abc road site karachi",
            distance: "6km",
            extraSkills: "photoshop-designer",
            profession: "web-developer",
            otherCourse: {
                courseName: "abc",
                institute: "abc",
                courseFee: 2000,
                instituteEmail: "abc@gmail.com",
                timing: "11aM-1PM",
                distance: "2km",
                duration: "8 months"
            },
            traveling: "persnol-bike",
            refreance: "through friend"
        }
    ],
    sponsors: [
        {
            name: "Engro",
            description: "A worldwide company",
            amount: "5,66596",
        }
    ],
    manager: [
        {
            name: "TUBA MOHSIN",
            qualification: "BSC",
            contact: 032145625,
            email: "tubamohsin@gmail.com"
        }
    ],
    ceo: [
        {
            name: "Sadaf",
            contact: 031322522,
            email: "sadaf@gmail.com"
        }
    ],
    duration: "8months",
    batchNo: 2019,
    faculty: [
        {
            name: "SarahAhmed",
            qualification: "Masters",
            about: "",
            contact: 03261136,
            email: "sarah@gmail.com",
        }
    ],
    ambassadors: [
        {
            name: "Arsala",
            qualification: "BSC",
            contact: 0327111366,
            email: "arsala@gmail.com"
        },
        {
            name: "Noreen Naz",
            qualification: "BSC",
            contact: 0315567323,
            email: "Noreen@gmail.com"
        },
        {
            name: "Kher-un-Nisa",
            qualification: "BSC",
            contact: 031656235,
            email: "kherunNisa@gmail.com"
        },
        {
            name: "Ali",
            qualification: "BSC",
            contact: 031256522,
            email: "ali@gmail.com"
        },
        {
            name: "wali",
            qualification: "BSC",
            contact: 02323236232,
            email: "walid@gmail.com"
        }
    ],
    timings: "2pm-6pm",
    extraClass: "6pm-7:30pm",
    breakTime: "30minuts",
    fee: 500,
    classes: ["tuesday", "thursday", "saturday"],
    lifeskills: {
        classDay: "saturday",
        timing: "2pm-6pm",
        breakTime: "15-20minuts",
    },
    location: "Usman Institute of Technolgy, university road",
    syllabous: [
        {
            course: ["Html", "Css", "Javascript"],
            onlineCertification: "freeCodeChamp",
            book: "smarter way to learn javascript",
            selfLearning: ["w3school", "mds"]
        }
    ],
    projects: [
        {
            html: "any web-page stracture",
            css: "designing of web-pages",
            js: "functionality of web-sites"
        }
    ],
    events: ["Womens impoverment", "we love tech", "eid party"],
}